data_path: "/lvmdata/shared/SberVAE/data/latents/ImageNet2012_200__wan_2.1_official__resolution_256/"
results_dir: "dit-updates/dit-l-2-256__imagenet2012_200__wan_2.1_official"
vae: wan-official
model: DiT-L/2
image_size: 256
num_classes: 1000
epochs: 2000
global_batch_size: 64
global_seed: 0
num_workers: 8
log_every: 100
ckpt_every: 50000
sample_every: 5
cfg_scale: 4.0
num_sampling_steps: 250
